### ISSUE TITLE
ERROR: lazy loading failed for package 'V.PhyloMaker'

### ISSUE THREAD

**Issue by JonathonMifsud** [jinyizju/V.PhyloMaker#4]
Hi,

I am trying to install this package but running into this error. Any help would be greatly appreciated! 
`remotes::install_github("jinyizju/V.PhyloMaker")`

**Output:**

Downloading GitHub repo jinyizju/V.PhyloMaker@master
√  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpAzjM9F\remotes548c66a734f7\jinyizju-V.PhyloMaker-e250ac8/DESCRIPTION' ... 
-  preparing 'V.PhyloMaker':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'V.PhyloMaker_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/Administrator/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'V.PhyloMaker' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ape' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'V.PhyloMaker'
* removing 'C:/Users/Administrator/R/win-library/3.6/V.PhyloMaker'
Error: Failed to install 'V.PhyloMaker' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Administrator/AppData/Local/Temp/RtmpAzjM9F/file548c55d44b6b/V.PhyloMaker_0.1.0.tar.gz’ had non-zero exit status

**Comment by cassiabitencourt** [comment]
Yes, it happened to me also:

Installing package into ‘C:/Users/cabit/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'V.PhyloMaker' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ape' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'V.PhyloMaker'
* removing 'C:/Users/cabit/Documents/R/win-library/3.6/V.PhyloMaker'
Error: Failed to install 'V.PhyloMaker' from GitHub:
  (converted from warning) installation of package ‘C:/Users/cabit/AppData/Local/Temp/Rtmpo5tpHD/file1da032097cbe/V.PhyloMaker_0.1.0.tar.gz’ had non-zero exit status

Please, could you give me an updates?
Regards.

**Comment by Si-Chong** [comment]
Same with me.
I tried both:
devtools::install_github("jinyizju/V.PhyloMaker")
remotes::install_github("jinyizju/V.PhyloMaker")

It wasn't a problem last year. My R version is 3.6.2
Could anybody help please?

**Comment by jinyizju** [comment]
Do not know exactly why you guys failed to install V.PhyloMaker. You could try install V.PhyloMaker in the latest version of R, which is R 3.6.3 at the moment, might work, if you have not already found the solution.

**Comment by Si-Chong** [comment]
Yes, now I updated my R version to 3.6.3 and everything is back to normal. I doubt why version 3.6.2 failed with the installation... But anyway, thank you for the help Dr Jin -- I am happy that I can use this fantastic package again.

**Comment by jinyizju** [comment]
Thanks for using the package, Si-Chong, I am glad to know you found the solution. Good luck.

**Comment by maordano** [comment]
I had the same problem
devtools::install_github("jinyizju/V.PhyloMaker") 
update the necessary packages and correct the problem for R 3.6.3 in Ubuntu
