### ISSUE TITLE
tip.label issue 

### ISSUE THREAD

**Issue by brunapazevedo** [jinyizju/V.PhyloMaker#7]
Hello! Thank you for the package. I'm having a small issue.

I have a list of 1300 species and I'm running the phylo.maker function using tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3". Everything seens perfect and the all the species that are not in the phylogeny appear as "bind" in the species.list status. However, nine of these species are not included in the tip.label.

Do you have any clue for what might be happening?

**Comment by jinyizju** [comment]
pls list the nine species that were not binded.

**Comment by brunapazevedo** [comment]
I think I solve the problem. I have some individuals in my sp.list that are identified only at the genus level. I find out that when I add "sp" after the genus (e.g.,"Deguelia sp"), all the other species are binded correctly.

The species failing to bind were "Deguelia costata", "Deguelia hatschbachii", "Homalolepis cedron", "Homalolepis subcymosa", "Moquiniastrum polymorphum", "Myracrodruon urundeuva",  "Stephanopodium blanchetianum", "Stephanopodium magnifolium" and "Thyrsodium spruceanum".

**Comment by jinyizju** [comment]
I see. So you have solved the problem. Thanks for listing the species anyway. Good luck with the research!
